# Generated by Django 4.1.2 on 2022-11-05 04:42

import api.models.account
import api.util.generators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.util.generators.gen_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(max_length=128)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "email_verificiation",
                    models.CharField(
                        default=api.models.account.verification_code, max_length=8
                    ),
                ),
                ("email_is_verified", models.BooleanField(default=False)),
                ("email_sent_ts", models.BigIntegerField(default=0)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("PARENT", "P"), ("STUDENT", "S"), ("OTHER", "O")],
                        max_length=20,
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(default=api.models.account.default_preferences),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.util.generators.gen_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nyc_id", models.CharField(blank=True, max_length=6, null=True)),
                ("name", models.CharField(default="No Name Provided", max_length=200)),
                ("desc", models.TextField(default="No Description Provided")),
                ("school_type", models.CharField(default="UNSET", max_length=32)),
                ("url", models.URLField()),
                (
                    "email",
                    models.CharField(default="noreply@shortlist.nyc", max_length=200),
                ),
                ("phone", models.CharField(max_length=32)),
                ("borough_code", models.IntegerField(default=0)),
                (
                    "address",
                    models.CharField(default="No Address Provided", max_length=200),
                ),
                ("district", models.IntegerField(default=0)),
                ("lat", models.FloatField(default=40.7128)),
                ("lon", models.FloatField(default=-74.006)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolDim",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("source", models.CharField(default="unset", max_length=100)),
                ("field", models.CharField(default="unset", max_length=100)),
                ("display_short", models.CharField(default="unset", max_length=100)),
                (
                    "display_long",
                    models.CharField(default="No Detail Provided", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolDimValue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "dim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.schooldim",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.school",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="schooldim",
            index=models.Index(fields=["field"], name="api_schoold_field_55e523_idx"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["nyc_id"], name="api_school_nyc_id_a742af_idx"),
        ),
        migrations.AddField(
            model_name="account",
            name="associates",
            field=models.ManyToManyField(blank=True, to="api.account"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["email"], name="api_account_email_73f779_idx"),
        ),
    ]
