# Generated by Django 4.1.2 on 2022-11-03 21:44

import api.models.account
import api.util.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.util.generators.gen_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "email_verificiation",
                    models.CharField(
                        default=api.models.account.verification_code, max_length=8
                    ),
                ),
                ("email_is_verified", models.BooleanField(default=False)),
                ("email_sent_ts", models.BigIntegerField(default=0)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("PARENT", "P"), ("STUDENT", "S"), ("OTHER", "O")],
                        max_length=20,
                    ),
                ),
                ("preferences", models.JSONField(default="{}")),
            ],
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["email"], name="api_account_email_73f779_idx"),
        ),
    ]
