# Generated by Django 4.1.2 on 2022-10-11 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('dbn', models.CharField(max_length=6, unique=True)),
                ('school_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=50)),
                ('school_type', models.CharField(choices=[('HS', 'High School'), ('HST', 'High School Transfer')], default='HS', max_length=3)),
                ('num_enrollment', models.PositiveIntegerField()),
                ('borough_name', models.CharField(max_length=15)),
                ('borough_code', models.CharField(choices=[('M', 'Manhattan'), ('X', 'Bronx'), ('R', 'Staten Island'), ('K', 'Brooklyn'), ('Q', 'Queens')], max_length=1)),
                ('phone_number', models.CharField(max_length=10)),
                ('primary_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('district_code', models.CharField(max_length=2)),
                ('neighborhood', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
