# Generated by Django 4.1.2 on 2022-10-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='neighborhood',
            field=models.CharField(max_length=50),
        ),
    ]
