# Generated by Django 4.1.2 on 2022-11-03 21:45

import api.models.account
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="preferences",
            field=models.JSONField(default=api.models.account.default_preferences),
        ),
    ]
