# Generated by Django 4.1.2 on 2022-11-05 23:20

import api.util.generators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school",
            options={"verbose_name": "School", "verbose_name_plural": "Schools"},
        ),
        migrations.AlterModelOptions(
            name="schooldim",
            options={
                "verbose_name": "School Dimension",
                "verbose_name_plural": "School Dimensions",
            },
        ),
        migrations.AlterModelOptions(
            name="schooldimvalue",
            options={
                "verbose_name": "School Dimension Value",
                "verbose_name_plural": "School Dimension Values",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.util.generators.gen_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank_asc", models.FloatField(default=100000)),
                ("seen_count", models.IntegerField(default=0)),
                ("current_accepted", models.BooleanField(default=False)),
                ("current_trashed", models.BooleanField(default=False)),
                ("ever_accepted", models.BooleanField(default=False)),
                ("ever_trashed", models.BooleanField(default=False)),
                ("associate_recommended", models.BooleanField(default=False)),
                ("scored_ts", models.BigIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.account"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
            },
        ),
    ]
