# Generated by Django 4.1.2 on 2022-11-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_school_options_alter_schooldim_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["rank_asc"], name="api_recomme_rank_as_97af60_idx"
            ),
        ),
    ]
