# Generated by Django 4.1.2 on 2022-11-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_account_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="associates",
            field=models.ManyToManyField(blank=True, to="api.account"),
        ),
    ]
