# Generated by Django 4.1.2 on 2022-11-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_recommendation_api_recomme_rank_as_97af60_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["seen_count"], name="api_recomme_seen_co_15cdd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["associate_recommended"], name="api_recomme_associa_5e8141_idx"
            ),
        ),
    ]
