# Generated by Django 4.1.2 on 2022-12-03 08:35

import api.models.shortlist
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_alter_recommendation_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shortlist",
            fields=[
                (
                    "shortlist_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "school_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(null=True),
                        blank=True,
                        default=list,
                        size=3,
                    ),
                ),
                ("shortlist_name", models.CharField(max_length=50)),
                (
                    "settings",
                    models.JSONField(default=api.models.shortlist.default_settings),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
