# Generated by Django 4.1.2 on 2022-12-03 08:51

import api.util.generators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_shortlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortlist",
            name="school_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    default=api.util.generators.gen_uuid, max_length=32, null=True
                ),
                blank=True,
                default=list,
                size=3,
            ),
        ),
    ]
