# Testing Create a Parent account
POST http://localhost:8000/account/create
content-type: application/json

{
  "email": "checkRecos@email.com",
  "preferredName": "my name is not important",
  "passwordHash": "123",
  "accountType": "PARENT"
}


POST https://1rct87m2md.execute-api.us-east-1.amazonaws.com/account/create
content-type: application/json

{
  "email": "moreNewEmails@sample.com",
  "preferredName": "Deployment Example",
  "passwordHash": "123",
  "accountType": "STUDENT"
}