language: generic

jobs:
  include:
    - name: Backend
      if: branch in (main,develop)
      env: TARGET=src/backend
      language: python
      python: 3.8.5
      install: pip install -r src/backend/requirements.txt
      script:
        - echo 'Not currently set up for deployment via Travis'

    - name: Frontend
      if: branch in (main,develop)
      env: TARGET=src/frontend
      language: node_js
      node_js:
        - 16
        
      script: 
        - echo 'Not currently set up for deployment via Travis'
    
