export const recommendations = [
  {
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Logan_High_School_%2848496033862%29.jpg/440px-Logan_High_School_%2848496033862%29.jpg",
    name: "Logan High School",
    borough: "Manhattan",
    link: "http://google.com",
    dimensions: [
      { name: "rigorous_instruction_rating", value: 0.77, simple: true },
      { name: "collaborative_teachers_rating", value: 0.75, simple: false },
      { name: "supportive_environment_rating", value: 0.69, simple: true },
      {
        name: "effective_school_leadership_rating",
        value: 0.68,
        simple: false,
      },
      {
        name: "strong_family_community_ties_rating",
        value: 0.82,
        simple: true,
      },
      { name: "trust_rating", value: 0.77, simple: false },
      { name: "student_achievement_rating", value: null, simple: false },
    ],
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Stuyvesant_HS_main_entrance_on_Chambers_Street.jpg/2560px-Stuyvesant_HS_main_entrance_on_Chambers_Street.jpg",
    name: "Stuyvesant High School Super Long School Name",
    borough: "West Village, Manhattan",
    dimensions: [
      { name: "rigorous_instruction_rating", value: 0.81, simple: true },
      { name: "collaborative_teachers_rating", value: 0.88, simple: false },
      { name: "supportive_environment_rating", value: 0.85, simple: true },
      {
        name: "effective_school_leadership_rating",
        value: 0.95,
        simple: false,
      },
      {
        name: "strong_family_community_ties_rating",
        value: 0.68,
        simple: true,
      },
      { name: "trust_rating", value: 0.91, simple: false },
      { name: "student_achievement_rating", value: null, simple: false },
    ],
  },
  {
    img: "https://www.google.com/images/branding/googlelogo/2x/googlelogo_light_color_272x92dp.png",
    name: "Google High School",
    borough: "Chelsea, Manhattan",
    dimensions: [
      { name: "rigorous_instruction_rating", value: 0.77, simple: true },
      { name: "collaborative_teachers_rating", value: 0.75, simple: false },
      { name: "supportive_environment_rating", value: 0.69, simple: true },
      {
        name: "effective_school_leadership_rating",
        value: 0.68,
        simple: false,
      },
      {
        name: "strong_family_community_ties_rating",
        value: 0.82,
        simple: true,
      },
      { name: "trust_rating", value: 0.77, simple: false },
      { name: "student_achievement_rating", value: null, simple: false },
    ],
  },
  {
    img: "https://live.staticflickr.com/7807/46061439155_6266fd342b_h.jpg",
    name: "Forest Hills High School",
    borough: "Queens",
    link: "https://www.foresthillshs.org/",
    dimensions: [
      { name: "rigorous_instruction_rating", value: 0.77, simple: true },
      { name: "collaborative_teachers_rating", value: 0.75, simple: false },
      { name: "supportive_environment_rating", value: 0.69, simple: true },
      {
        name: "effective_school_leadership_rating",
        value: 0.68,
        simple: false,
      },
      {
        name: "strong_family_community_ties_rating",
        value: 0.82,
        simple: true,
      },
      { name: "trust_rating", value: 0.77, simple: false },
      { name: "student_achievement_rating", value: null, simple: false },
    ],
    id: "0f903c4c-dd5a-48b2-ac5a-0e2c89184363",
  },
  {
    img: "https://thecity.brightspotcdn.com/dims4/default/397bfd9/2147483647/strip/false/crop/3000x1688+0+157/resize/1200x675!/quality/90/?url=https%3A%2F%2Fcdn.vox-cdn.com%2Fthumbor%2FFDZdRR65OQYH-SUgbTwxivBgIBU%3D%2F0x0%3A3000x2001%2F3000x2001%2Ffilters%3Afocal%281500x1001%3A1501x1002%29%2Fcdn.vox-cdn.com%2Fuploads%2Fchorus_asset%2Ffile%2F20045773%2Fnew_dorp_high_school.0.jpg",
    name: "New Dorp High School",
    borough: "Staten Island",
    link: "https://www.newdorphs.org/",
    dimensions: [
      { name: "rigorous_instruction_rating", value: 0.81, simple: true },
      { name: "collaborative_teachers_rating", value: 0.88, simple: false },
      { name: "supportive_environment_rating", value: 0.85, simple: true },
      {
        name: "effective_school_leadership_rating",
        value: 0.95,
        simple: false,
      },
      {
        name: "strong_family_community_ties_rating",
        value: 0.68,
        simple: true,
      },
      { name: "trust_rating", value: 0.91, simple: false },
      { name: "student_achievement_rating", value: null, simple: false },
    ],
    id: "0ae2a989-a1d0-4110-9d1f-42e420278b3d",
  },
  {
    img: "https://unhs.sharpschool.com/UserFiles/Servers/Server_21018672/Templates/image-bg-03.jpg",
    name: "University Neighborhood High School",
    borough: "Manhattan",
    link: "https://universityneighborhoodhighschool.org/",
    dimensions: [
      { name: "rigorous_instruction_rating", value: 0.87, simple: true },
      { name: "collaborative_teachers_rating", value: 0.93, simple: false },
      { name: "supportive_environment_rating", value: 0.82, simple: true },
      {
        name: "effective_school_leadership_rating",
        value: 0.95,
        simple: false,
      },
      {
        name: "strong_family_community_ties_rating",
        value: 0.87,
        simple: true,
      },
      { name: "trust_rating", value: 0.94, simple: false },
      { name: "student_achievement_rating", value: null, simple: false },
    ],
    id: "4da02876-8041-4010-a4cf-0d303ac5cd6c",
  },
  {
    img: "https://scholamatch-uploads-prod.s3.amazonaws.com/school/34822/30401fb8-71db-48a0-972c-af50c9f0238e.png",
    name: "Brooklyn Community Arts & Media High School (BCAM)",
    borough: "Brooklyn",
    link: "http://www.bcamhs.org/",
    dimensions: [
      { name: "rigorous_instruction_rating", value: 0.78, simple: true },
      { name: "collaborative_teachers_rating", value: 0.85, simple: false },
      { name: "supportive_environment_rating", value: 0.65, simple: true },
      {
        name: "effective_school_leadership_rating",
        value: 0.5,
        simple: false,
      },
      {
        name: "strong_family_community_ties_rating",
        value: 0.91,
        simple: true,
      },
      { name: "trust_rating", value: 0.9, simple: false },
      { name: "student_achievement_rating", value: null, simple: false },
    ],
    id: "9861b295-42ec-42ab-aa3e-160d563b13ae",
  },
];
