export const shortLists = [
  {
    id: "ad5e4da6-ce1a-4f82-91da-7e076164faf4",
    settings: {
      name: "Target",
      color: "#ecf0f3",
      icon: { value: "token", color: "black" },
    },
    schools: [
      {
        schoolMetadata: {
          id: "5e195f827f274bb68d75c73f629b1fef",
          nycId: "21K410",
          name: "Abraham Lincoln High School",
          desc: "Abraham Lincoln High School prepares students for the world of today. Our small learning communities and advisories offer all students supports and challenges. Lincoln students become Lincoln Citizens-ready to play an important role in their future colleges and communities.",
          schoolType: "PUBLIC",
          url: "www.alhs.nyc",
          email: "admissions@alhs.nyc",
          phone: "7183337400",
          boroughCode: 2,
          address: "2800 Ocean Parkway, Brooklyn, NY 11235",
          district: 21,
          lat: 40.582863,
          lon: -73.968218,
        },
        schoolDimensions: [
          {
            dimId: 1,
            dimShort: "Start Time",
            value: "07:48:00",
            isSimple: false,
          },
          {
            dimId: 2,
            dimShort: "End Time",
            value: "15:28:00",
            isSimple: false,
          },
          {
            dimId: 3,
            dimShort: "Accessibility",
            value: "Partially Accessible",
            isSimple: false,
          },
          {
            dimId: 4,
            dimShort: "Magnet",
            value: false,
            isSimple: false,
          },
          {
            dimId: 5,
            dimShort: "Enrollment",
            value: 1817,
            isSimple: false,
          },
          {
            dimId: 6,
            dimShort: "Grade Years",
            value: "9 to 12",
            isSimple: false,
          },
          {
            dimId: 7,
            dimShort: "Street Address",
            value: "2800 Ocean Parkway",
            isSimple: false,
          },
          {
            dimId: 8,
            dimShort: "City",
            value: 2,
            isSimple: false,
          },
          {
            dimId: 9,
            dimShort: "State",
            value: 1,
            isSimple: false,
          },
          {
            dimId: 10,
            dimShort: "Zip Code",
            value: 11235,
            isSimple: false,
          },
          {
            dimId: 11,
            dimShort: "Rigorous Instruction",
            value: 0.75,
            isSimple: false,
          },
          {
            dimId: 12,
            dimShort: "Collaborative Teachers",
            value: 0.89,
            isSimple: false,
          },
          {
            dimId: 13,
            dimShort: "Supportive Environment",
            value: 0.81,
            isSimple: false,
          },
          {
            dimId: 14,
            dimShort: "Effective School Leadership",
            value: 0.89,
            isSimple: false,
          },
          {
            dimId: 15,
            dimShort: "Strong Family-Community Ties",
            value: 0.82,
            isSimple: false,
          },
          {
            dimId: 16,
            dimShort: "Trust",
            value: 0.88,
            isSimple: false,
          },
          {
            dimId: 17,
            dimShort: "Average Attendance Rate",
            value: 0.86,
            isSimple: false,
          },
          {
            dimId: 18,
            dimShort: "4-Year Graduation Rate",
            value: 0.864,
            isSimple: false,
          },
          {
            dimId: 19,
            dimShort: "Postsecondary Enrollment Rate (6 months)",
            value: 0.615,
            isSimple: false,
          },
          {
            dimId: 20,
            dimShort: "Average SAT Score: Math",
            value: 442,
            isSimple: false,
          },
          {
            dimId: 21,
            dimShort: "Average SAT Score: Reading & Writing",
            value: 438,
            isSimple: false,
          },
        ],
      },
    ],
  },
  {
    id: "cd1f2e04-f458-44da-8f54-df65737ce8ff",
    settings: {
      name: "Dream",
      color: "#bec7e7",
      icon: { value: "token", color: "black" },
    },
    schools: [
      {
        schoolMetadata: {
          id: "5e195f827f274bb68d75c73f629b1fef",
          nycId: "21K410",
          name: "Abraham Lincoln High School",
          desc: "Abraham Lincoln High School prepares students for the world of today. Our small learning communities and advisories offer all students supports and challenges. Lincoln students become Lincoln Citizens-ready to play an important role in their future colleges and communities.",
          schoolType: "PUBLIC",
          url: "www.alhs.nyc",
          email: "admissions@alhs.nyc",
          phone: "7183337400",
          boroughCode: 2,
          address: "2800 Ocean Parkway, Brooklyn, NY 11235",
          district: 21,
          lat: 40.582863,
          lon: -73.968218,
        },
        schoolDimensions: [
          {
            dimId: 1,
            dimShort: "Start Time",
            value: "07:48:00",
            isSimple: false,
          },
          {
            dimId: 2,
            dimShort: "End Time",
            value: "15:28:00",
            isSimple: false,
          },
          {
            dimId: 3,
            dimShort: "Accessibility",
            value: "Partially Accessible",
            isSimple: false,
          },
          {
            dimId: 4,
            dimShort: "Magnet",
            value: false,
            isSimple: false,
          },
          {
            dimId: 5,
            dimShort: "Enrollment",
            value: 1817,
            isSimple: false,
          },
          {
            dimId: 6,
            dimShort: "Grade Years",
            value: "9 to 12",
            isSimple: false,
          },
          {
            dimId: 7,
            dimShort: "Street Address",
            value: "2800 Ocean Parkway",
            isSimple: false,
          },
          {
            dimId: 8,
            dimShort: "City",
            value: 2,
            isSimple: false,
          },
          {
            dimId: 9,
            dimShort: "State",
            value: 1,
            isSimple: false,
          },
          {
            dimId: 10,
            dimShort: "Zip Code",
            value: 11235,
            isSimple: false,
          },
          {
            dimId: 11,
            dimShort: "Rigorous Instruction",
            value: 0.75,
            isSimple: false,
          },
          {
            dimId: 12,
            dimShort: "Collaborative Teachers",
            value: 0.89,
            isSimple: false,
          },
          {
            dimId: 13,
            dimShort: "Supportive Environment",
            value: 0.81,
            isSimple: false,
          },
          {
            dimId: 14,
            dimShort: "Effective School Leadership",
            value: 0.89,
            isSimple: false,
          },
          {
            dimId: 15,
            dimShort: "Strong Family-Community Ties",
            value: 0.82,
            isSimple: false,
          },
          {
            dimId: 16,
            dimShort: "Trust",
            value: 0.88,
            isSimple: false,
          },
          {
            dimId: 17,
            dimShort: "Average Attendance Rate",
            value: 0.86,
            isSimple: false,
          },
          {
            dimId: 18,
            dimShort: "4-Year Graduation Rate",
            value: 0.864,
            isSimple: false,
          },
          {
            dimId: 19,
            dimShort: "Postsecondary Enrollment Rate (6 months)",
            value: 0.615,
            isSimple: false,
          },
          {
            dimId: 20,
            dimShort: "Average SAT Score: Math",
            value: 442,
            isSimple: false,
          },
          {
            dimId: 21,
            dimShort: "Average SAT Score: Reading & Writing",
            value: 438,
            isSimple: false,
          },
        ],
      },
    ],
  },
  {
    id: "d8ad5d3f-0b9b-476a-92f1-6733e1fbc876",
    settings: {
      name: "Easy",
      color: "#bcd6a2",
      icon: { value: "token", color: "black" },
    },
    schools: [
      {
        schoolMetadata: {
          id: "5e195f827f274bb68d75c73f629b1fef",
          nycId: "21K410",
          name: "Abraham Lincoln High School",
          desc: "Abraham Lincoln High School prepares students for the world of today. Our small learning communities and advisories offer all students supports and challenges. Lincoln students become Lincoln Citizens-ready to play an important role in their future colleges and communities.",
          schoolType: "PUBLIC",
          url: "www.alhs.nyc",
          email: "admissions@alhs.nyc",
          phone: "7183337400",
          boroughCode: 2,
          address: "2800 Ocean Parkway, Brooklyn, NY 11235",
          district: 21,
          lat: 40.582863,
          lon: -73.968218,
        },
        schoolDimensions: [
          {
            dimId: 1,
            dimShort: "Start Time",
            value: "07:48:00",
            isSimple: false,
          },
          {
            dimId: 2,
            dimShort: "End Time",
            value: "15:28:00",
            isSimple: false,
          },
          {
            dimId: 3,
            dimShort: "Accessibility",
            value: "Partially Accessible",
            isSimple: false,
          },
          {
            dimId: 4,
            dimShort: "Magnet",
            value: false,
            isSimple: false,
          },
          {
            dimId: 5,
            dimShort: "Enrollment",
            value: 1817,
            isSimple: false,
          },
          {
            dimId: 6,
            dimShort: "Grade Years",
            value: "9 to 12",
            isSimple: false,
          },
          {
            dimId: 7,
            dimShort: "Street Address",
            value: "2800 Ocean Parkway",
            isSimple: false,
          },
          {
            dimId: 8,
            dimShort: "City",
            value: 2,
            isSimple: false,
          },
          {
            dimId: 9,
            dimShort: "State",
            value: 1,
            isSimple: false,
          },
          {
            dimId: 10,
            dimShort: "Zip Code",
            value: 11235,
            isSimple: false,
          },
          {
            dimId: 11,
            dimShort: "Rigorous Instruction",
            value: 0.75,
            isSimple: false,
          },
          {
            dimId: 12,
            dimShort: "Collaborative Teachers",
            value: 0.89,
            isSimple: false,
          },
          {
            dimId: 13,
            dimShort: "Supportive Environment",
            value: 0.81,
            isSimple: false,
          },
          {
            dimId: 14,
            dimShort: "Effective School Leadership",
            value: 0.89,
            isSimple: false,
          },
          {
            dimId: 15,
            dimShort: "Strong Family-Community Ties",
            value: 0.82,
            isSimple: false,
          },
          {
            dimId: 16,
            dimShort: "Trust",
            value: 0.88,
            isSimple: false,
          },
          {
            dimId: 17,
            dimShort: "Average Attendance Rate",
            value: 0.86,
            isSimple: false,
          },
          {
            dimId: 18,
            dimShort: "4-Year Graduation Rate",
            value: 0.864,
            isSimple: false,
          },
          {
            dimId: 19,
            dimShort: "Postsecondary Enrollment Rate (6 months)",
            value: 0.615,
            isSimple: false,
          },
          {
            dimId: 20,
            dimShort: "Average SAT Score: Math",
            value: 442,
            isSimple: false,
          },
          {
            dimId: 21,
            dimShort: "Average SAT Score: Reading & Writing",
            value: 438,
            isSimple: false,
          },
        ],
      },
      {
        img: "https://scholamatch-uploads-prod.s3.amazonaws.com/school/34822/30401fb8-71db-48a0-972c-af50c9f0238e.png",
        name: "Brooklyn Community Arts & Media High School (BCAM)",
        borough: "Brooklyn",
        link: "http://www.bcamhs.org/",
        dimensions: [
          { name: "rigorous_instruction_rating", value: 0.78, simple: true },
          { name: "collaborative_teachers_rating", value: 0.85, simple: false },
          { name: "supportive_environment_rating", value: 0.65, simple: true },
          {
            name: "effective_school_leadership_rating",
            value: 0.5,
            simple: false,
          },
          {
            name: "strong_family_community_ties_rating",
            value: 0.91,
            simple: true,
          },
          { name: "trust_rating", value: 0.9, simple: false },
          { name: "student_achievement_rating", value: null, simple: false },
        ],
        id: "9861b295-42ec-42ab-aa3e-160d563b13ae",
      },
    ],
  },
];
