name: LINTER - JAVASCRIPT

# Lint on all pushes anywhere
# Lint on pull requests to develop
on:
  push:
    branches:
      - '*'
    paths:
      - 'src/frontend/**'
  pull_request:
    branches:
      - 'develop'

jobs:
  run_js_linter:
    # Github uses ubuntu-20.04 as 'latest' 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: NPM Install
        working-directory: ./src/frontend/shortlist
        run: npm install

      - name: ESLint
        working-directory: ./src/frontend/shortlist
        run: npm run lint -- --no-fix "./src/**"
