name: UNIT TESTS - PYTHON


# Test on all pushes anywhere
# Test on pull requests to develop
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  run_py_unit:
    # Github uses ubuntu-20.04 as 'latest' 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Requirements
        working-directory: ./src/backend
        run: |
          pip3 install -r requirements.txt

      - name: Run Django Tests
        working-directory: ./src/backend/server/
        env:
          SHORTLIST_RDS_ENDPOINT: ${{ secrets.SHORTLIST_RDS_ENDPOINT }}
          SHORTLIST_RDS_DB: ${{ secrets.SHORTLIST_RDS_DB}}
          SHORTLIST_RDS_PORT: ${{ secrets.SHORTLIST_RDS_PORT }}
          SHORTLIST_RDS_USER: ${{ secrets.SHORTLIST_RDS_USER }}
          SHORTLIST_RDS_PASSWORD: ${{ secrets.SHORTLIST_RDS_PASSWORD }}
          SHORTLIST_DJANGO_SECRET: ${{ secrets.SHORTLIST_DJANGO_SECRET }}
          SHORTLIST_EMAIL_SMTP_HOST: ${{ secrets.SHORTLIST_EMAIL_SMTP_HOST }}
          SHORTLIST_EMAIL_HOST_USER: ${{ secrets.SHORTLIST_EMAIL_HOST_USER }}
          SHORTLIST_EMAIL_HOST_PASSWORD: ${{ secrets.SHORTLIST_EMAIL_HOST_PASSWORD }}
        run: |
          python3 manage.py test
