name: UNIT TESTS - JAVASCRIPT

# Test on all pushes anywhere
# Test on pull requests to develop
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  run_js_unit:
    # Github uses ubuntu-20.04 as 'latest' 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: NPM Install
        working-directory: ./src/frontend/shortlist
        run: npm install

      - name: NPM test:unit (vitest)
        working-directory: ./src/frontend/shortlist
        run: npm run test:unit -- --run --coverage --passWithNoTests
