# Generated by Django 4.1.2 on 2022-11-13 02:30

import authentication.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="associates",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(default=authentication.models.default_preferences),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("PARENT", "P"), ("STUDENT", "S"), ("OTHER", "O")],
                default="P",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
