# Generated by Django 4.1.2 on 2022-11-13 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_associates_user_preferences_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
