# Generated by Django 4.1.2 on 2022-11-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_user_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_uuid",
        ),
    ]
